### ISSUE TITLE
run NcxReader.py  raise a error

### ISSUE THREAD

**Issue by brucmao** [HyperSine/how-does-navicat-encrypt-password#25]
```
python3 .\NcxReader.py c:\Users\brucm\Desktop\connections.ncx
---------------------test-jt----------------------
Connection Type  = MYSQL
Host             = 10.10.10.10
Port             = 3306
UserName         = root
Traceback (most recent call last):
  File "C:\Apps\how-does-navicat-encrypt-password\python3\NcxReader.py", line 114, in <module>
    exit(Main(len(sys.argv), sys.argv))
  File "C:\Apps\how-does-navicat-encrypt-password\python3\NcxReader.py", line 105, in Main
    print('%-16s = %s' % ('Password', TryDecrypt(cipher, conn.attrib['Password'])))
KeyError: 'Password'
```

**Comment by HyperSine** [comment]
It seems the connections.ncx file doesn't have `Password` fields. Are you sure the connections.ncx file is exported with password?

**Comment by brucmao** [comment]
It's my fault.I forgot to check the export password option.
but there is a error
```
---------------------test-jt----------------------
Connection Type  = MYSQL
Host             = 10.10.10.10
Port             = 3306
UserName         = root
Traceback (most recent call last):
  File "C:\Apps\how-does-navicat-encrypt-password\python3\NcxReader.py", line 114, in <module>
    exit(Main(len(sys.argv), sys.argv))
  File "C:\Apps\how-does-navicat-encrypt-password\python3\NcxReader.py", line 105, in Main
    print('%-16s = %s' % ('Password', TryDecrypt(cipher, conn.attrib['Password'])))
  File "C:\Apps\how-does-navicat-encrypt-password\python3\NcxReader.py", line 82, in TryDecrypt
    raise ValueError('Decryption failed!')
ValueError: Decryption failed!
```
>navicat 16.1.3
>python 3.10.4

**Comment by HyperSine** [comment]
It seems there are some typos in NcxReader.py that raised the exception. It should be fixed now. Please git pull to the latest and try again.

**Comment by brucmao** [comment]
It works now,thanks.
